development:
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: depot_store_development
  username: root
  password: 12345678

test:
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: depot_store_test
  username: root
  password: 12345678

production:
 #database: <%= ENV['DATABASE_URL'] %>
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: depot_store_production
  username: root
  password: 12345678

